version: '3.8'

services:
  fa-api:
    container_name: fa-api
    build:
      context: ./FilmAppka - BackEnd
      dockerfile: Dockerfile
    networks:
      - conn
    ports:
     - "5000:5000"
     - "5001:5001"
    expose:
      - 5000
      - 5001
    depends_on:
      - fa-db

  fa-db:
    container_name: fa-db
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    volumes:
      - ./bak/backupV2.bacpac:/tmp/backupV2.bacpac
      - ./bak/FilmappkaDB.bak:/tmp/FilmappkaDB.bak
    networks:
      - conn
    ports:
      - "1433:1433"
    expose:
      - 1443
    environment:
        SA_PASSWORD: "S3cur3P@ssW0rd!"
        ACCEPT_EULA: "Y"

  ffr-db:
    container_name: ffr-db
    image: mongo
    command: mongod --port 27000
    networks:
      - conn
    expose:
      - 27000
    ports:
      - "27000:27000"

  # db:
  #   container_name: db
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: 'FilmAppkaDB'
  #     # So you don't have to use root, but you can if you like
  #     MYSQL_USER: 'user'
  #     # You can use whatever password you like
  #     MYSQL_PASSWORD: 'root'
  #     # Password for root access
  #     MYSQL_ROOT_PASSWORD: 'root'
  #   ports:
  #     # <Port exposed> : < MySQL Port running inside container>
  #     - '3306:3306'
  #   expose:
  #     # Opens port 3306 on the container
  #     - '3306'

  ffr-api:
    container_name: ffr-api
    depends_on:
      - ffr-db
      - fa-api
    build:
      context: ./ffr
      target: api
    networks:
      - conn
    expose:
      - 9000
    ports:
      - "9000:9000"

networks:
  conn:
    driver: bridge