version: '3.8'

services:
  ffr-db:
    container_name: ffr-db
    image: mongo
    command: mongod --port 27000
    expose:
      - 27000
    ports:
      - "27000:27000"

  ffr-api:
    container_name: ffr-api
    depends_on:
      - ffr-db
    build:
      context: .
      target: api
    expose:
      - 6666
    ports:
      - "6666:6666"